version: '3'
services:
        web:
                image: portfolio
                build: .
                container_name: portfolio
                restart: always
                ports:
                        - "8080:80"
